// this file That generate the final report

// to use this jars it is a must ti=o download them it is itext5.5.0
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;

import com.itextpdf.text.Anchor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfWriter;

public class PdfJenerator{
	
	PdfJenerator(ProcessGraph pathFinder, String image) throws DocumentException, MalformedURLException, IOException{
	Document document = new Document(PageSize.A4, 50, 50, 50, 50);
	PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream("report.pdf"));
	document.open();
	Anchor anchorTarget = new Anchor("This report is generated by YAK tool.");
	anchorTarget.setName("End of the report");
	Paragraph paragraph1 = new Paragraph();
	paragraph1.setSpacingBefore(50);
	paragraph1.add(anchorTarget);
	document.add(paragraph1);
	document.add(new Paragraph("\n\nThis report shows three main topics\n        1-Simple paths\n        2-Prime Paths\n        3-Test paths\n        4-the visiualization of the graph\n.",FontFactory.getFont(FontFactory.COURIER, 20, Font.NORMAL,new CMYKColor(150, 255, 0, 0))));
	Paragraph title1 = new Paragraph("Chapter 1",FontFactory.getFont(FontFactory.HELVETICA,18, Font.BOLDITALIC, new CMYKColor(0, 255, 255,17)));
	Chapter chapter1 = new Chapter(title1, 1);
	chapter1.setNumberDepth(1);
	
	Paragraph title11 = new Paragraph("The simple paths",FontFactory.getFont(FontFactory.HELVETICA, 16, Font.BOLD,new CMYKColor(0, 255, 255,17)));
	Section section1 = chapter1.addSection(title11);
	Paragraph someSectionText = new Paragraph(pathFinder.getSimplePathString());
	section1.add(someSectionText);
	
	Paragraph title12 = new Paragraph("The prime paths.",FontFactory.getFont(FontFactory.HELVETICA, 16, Font.BOLD,new CMYKColor(0, 255, 255,17)));
	Section section2 = chapter1.addSection(title12);
	Paragraph someSectionText2 = new Paragraph(pathFinder.getPrimePathString());
	section2.add(someSectionText2);
	
	Paragraph title13 = new Paragraph("The test paths.",FontFactory.getFont(FontFactory.HELVETICA, 16, Font.BOLD,new CMYKColor(0, 255, 255,17)));
	Section section3 = chapter1.addSection(title13);
	Paragraph someSectionText3 = new Paragraph(pathFinder.getTestPathString());
	section3.add(someSectionText3);
	
	Paragraph title14 = new Paragraph("\nThe Graph.",FontFactory.getFont(FontFactory.HELVETICA, 16, Font.BOLD,new CMYKColor(0, 255, 255,17)));
	Section section4 = chapter1.addSection(title14);
	Image image2 = Image.getInstance(image);
    image2.scaleAbsolute(150f, 400f);
    section4.add(image2);
    
    Paragraph title2 = new Paragraph("Made by\n\tAhmedAlaa\n\tYousef Hamza\n\tKhled Essam\n",FontFactory.getFont(FontFactory.HELVETICA, 16, Font.BOLD,new CMYKColor(0, 255, 0, 0)));
    Section section5 = chapter1.addSection(title2);
    title2.setSpacingBefore(50);
    Anchor anchor2 = new Anchor("     \t\t\t\t\t                               The End");
    anchor2.setReference("#BackToTop");
    section5.add(anchor2);
    document.add(chapter1);
    document.close();
    writer.close();
	}
}
